# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

2021-07-09 22:14:46.790249: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-09 22:14:46.790274: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('CCPP/Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)
print (y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Encoding categorical data

Label Encoding the "Gender" column

One Hot Encoding the "Geography" column

### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential() #esqueleto de la red neuronal

2021-07-09 22:14:48.918579: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-07-09 22:14:48.918603: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-07-09 22:14:48.918623: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (deneb): /proc/driver/nvidia/version does not exist
2021-07-09 22:14:48.918802: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Adding the input layer and the first hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN on the Training set

In [11]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

2021-07-09 22:14:49.011303: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-07-09 22:14:49.032289: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 1999965000 Hz


Epoch 1/100
240/240 [==============================] - 1s 643us/step - loss: 1365.0908
Epoch 2/100
240/240 [==============================] - 0s 776us/step - loss: 468.7411
Epoch 3/100
240/240 [==============================] - 0s 719us/step - loss: 397.6910
Epoch 4/100
240/240 [==============================] - 0s 789us/step - loss: 323.4094
Epoch 5/100
240/240 [==============================] - 0s 767us/step - loss: 251.5004
Epoch 6/100
240/240 [==============================] - 0s 752us/step - loss: 186.7885
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 130.6086
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 87.8216
Epoch 9/100
240/240 [==============================] - 0s 918us/step - loss: 58.9180
Epoch 10/100
240/240 [==============================] - 0s 800us/step - loss: 42.2388
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 33.4186
Epoch 12/100
240/240 [==============================] - 0s 1m

240/240 [==============================] - 0s 852us/step - loss: 26.7791
Epoch 97/100
240/240 [==============================] - 0s 727us/step - loss: 27.0044
Epoch 98/100
240/240 [==============================] - 0s 696us/step - loss: 27.0602
Epoch 99/100
240/240 [==============================] - 0s 742us/step - loss: 26.5447
Epoch 100/100
240/240 [==============================] - 0s 753us/step - loss: 27.6466


## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[431.48 431.23]
 [462.58 460.01]
 [466.08 461.14]
 ...
 [473.34 473.26]
 [440.03 438.  ]
 [459.29 463.28]]
